<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.4" tiledversion="1.4.0" name="full tilemap" tilewidth="16" tileheight="16" tilecount="72" columns="9">
 <image source="full tilemap.png" trans="ff00ff" width="144" height="128"/>
 <tile id="0" type="gold"/>
 <tile id="1" type="barrel"/>
 <tile id="2" type="bookshelf"/>
 <tile id="3" type="flag-green"/>
 <tile id="4" type="flag-red"/>
 <tile id="5" type="key"/>
 <tile id="6" type="jar-green"/>
 <tile id="7" type="jar-red"/>
 <tile id="8" type="jar"/>
 <tile id="9" type="table"/>
 <tile id="10" type="table"/>
 <tile id="11" type="floor"/>
 <tile id="12" type="floor"/>
 <tile id="15" type="floor"/>
 <tile id="16" type="floor"/>
 <tile id="17" type="floor"/>
 <tile id="18" type="floor"/>
 <tile id="19" type="floor"/>
 <tile id="20" type="floor"/>
 <tile id="21" type="floor"/>
 <tile id="22" type="floor"/>
 <tile id="23" type="floor"/>
 <tile id="24" type="floor"/>
 <tile id="26" type="floor"/>
 <tile id="27" type="floor"/>
 <tile id="29" type="floor"/>
 <tile id="30" type="floor"/>
 <tile id="31" type="floor"/>
 <tile id="32" type="floor"/>
 <tile id="33" type="floor"/>
 <tile id="35" type="floor"/>
 <tile id="39" type="wall"/>
 <tile id="40" type="wall"/>
 <tile id="42" type="wall"/>
 <tile id="43" type="wall"/>
 <tile id="44" type="wall"/>
 <tile id="48" type="wall"/>
 <tile id="49" type="wall"/>
 <tile id="51" type="wall"/>
 <tile id="52" type="wall"/>
 <tile id="53" type="wall"/>
 <tile id="55" type="wall"/>
 <tile id="56" type="wall"/>
 <tile id="57" type="wall"/>
 <tile id="58" type="wall"/>
 <tile id="59" type="wall"/>
 <tile id="61" type="wall"/>
 <tile id="62" type="wall"/>
 <tile id="64" type="wall"/>
 <tile id="65" type="wall"/>
 <tile id="68" type="wall"/>
</tileset>
